### ISSUE TITLE
Configuration file

### ISSUE THREAD

**Issue by Ashwani-k101** [Kynetics/uf-android-client#16]
hello there, I am Stuck with a problem. My Update Factory app is not reding configuration file. But the configuration file is present at the location from where it needs to read.Is there suggesstions for this problem.

**Comment by Ashwani-k101** [comment]
Hello There, i am giving the url of logcat pastebin

https://pastebin.com/vaf8RX96

**Comment by diegorondini** [comment]
It seems the file is there but the service can't access it:
```
06-13 11:43:31.742  2934  2934 I conf1   : sdcard/UpdateFactoryConfiguration/ufConf.conf
06-13 11:43:31.745  2934  2934 I LOG1    : file found
06-13 11:43:31.747  2934  2934 W System.err: java.io.FileNotFoundException: sdcard/UpdateFactoryConfiguration/ufConf.conf: open failed: EACCES (Permission denied)
```

Can you provide the output of the following commands?

```
adb shell ls /sdcard/UpdateFactoryConfiguration/ufConf.conf
```
and:
```
adb shell getenforce
```
?

**Comment by Ashwani-k101** [comment]
hello there, I have tried giving permission for read, write and manage external storage and and gave  permission in apps and notification . It was working on emulator but it is not working on a hardware device i have.Please suggest any solution.

**Comment by diegorondini** [comment]
Hi,

glad that you are able to make it work in the emulator. You should ask for support to the provider of the Android OS image for your hardware, this is probably SELinux blocking access.

Regards

**Comment by Ashwani-k101** [comment]
Hi,
I was able to make UpdateFactory read conf file in Android 11 API 30 by giving read, write and manage permission in manifest file and giving permission from app & notification . Is there any way to make UpdateFactory read conf file on Android 10 API 29?
