### ISSUE TITLE
Update Factory

### ISSUE THREAD

**Issue by Shekhar6363** [Kynetics/uf-android-client#17]
hi, I have a device having Android 10 . I am trying to read configuration file on it , but it is not reading. on  android 11 API 30 emulator it is reading configuration file . please suggest some solution ,so that my device also can read configuraion file.

**Comment by diegorondini** [comment]
Hi,

as already mentioned you should:
1. check permissions
2. check the status of SELinux
3. post the logs

https://gitter.im/eclipse/hawkbit?at=6256b890161ffc40d70022bb
https://github.com/Kynetics/uf-android-client/issues/16#issuecomment-1152462592
https://github.com/Kynetics/uf-android-client/issues/16#issuecomment-1168385028

Anyway this is NOT an issue of the uf-android-client, so **you should ask for support to the provider of the Android OS image for your hardware**.
