### ISSUE TITLE
Trying to deploy OS update facing issue

### ISSUE THREAD

**Issue by Ashish080** [Kynetics/uf-android-client#21]
Hello there, this is the log file of UF service. I am trying perform A/B update on my system there is some issue.

AndroidMessageListener: Updating
 D UFSharedPreferences: Moving sharedPreferences to encrypted sharedPreferences
  D UFSharedPreferences: Moving sharedPreferences to plain sharedPreferences
   D OtaUpdater: apply module MOB_SM_0.0.10 1 of type os
   D OtaUpdater: install artifact sb52-ota-mp1V9181.zip from file /data/cache/update_factory/artifacts/305/dc7f492b1d9665339f98693a88215543
  D CurrentUpdateState: Using slot named: _a
 D LOG1    : LAST_SLOT: _a
  D ABOtaInstaller: FILE_HASH=gE4KAVOJoUvxC6pottTxFxh2RkOtS+7LBssP+jcw3KE=, FILE_SIZE=617949303, METADATA_HASH=86yr9fTysgWiCq0atTFRGa/DCO0gZBbZ+fhRrJqCr9o=, METADATA_SIZE=50633
E Update Factory Client: Error processing message in actor updateManager. error: class java.lang.NullPointerException message: Attempt to invoke interface method 'boolean android.os.IUpdateEngine.bind(android.os.IUpdateEngineCallback)' on a null object reference [::0] Thread[DefaultDispatcher-worker-8,5,main]
  D Update Factory Client: Attempt to invoke interface method 'boolean android.os.IUpdateEngine.bind(android.os.IUpdateEngineCallback)' on a null object reference [::0] Thread[DefaultDispatcher-worker-8,5,main]
 D Update Factory Client: java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.os.IUpdateEngine.bind(android.os.IUpdateEngineCallback)' on a null object reference
 D Update Factory Client: 	at android.os.UpdateEngine.bind(UpdateEngine.java:252)
 D Update Factory Client: 	at android.os.UpdateEngine.bind(UpdateEngine.java:263)
 D Update Factory Client: 	at com.kynetics.uf.android.update.system.ABOtaInstaller.install(ABOtaInstaller.kt:150)
 D Update Factory Client: 	at com.kynetics.uf.android.update.system.ABOtaInstaller.install(ABOtaInstaller.kt:35)
 D Update Factory Client: 	at com.kynetics.uf.android.update.system.OtaUpdater.applyUpdate(OtaUpdater.kt:49)
D Update Factory Client: 	at com.kynetics.uf.android.update.AndroidUpdater.apply(AndroidUpdater.kt:20)
D Update Factory Client: 	at com.kynetics.updatefactory.ddiclient.core.actors.UpdateManager.update(UpdateManager.kt:73)
 D Update Factory Client: 	at com.kynetics.updatefactory.ddiclient.core.actors.UpdateManager.access$update(UpdateManager.kt:22)
 D Update Factory Client: 	at com.kynetics.updatefactory.ddiclient.core.actors.UpdateManager$beforeStartReceive$1.invokeSuspend(UpdateManager.kt:38)
 D Update Factory Client: 	at com.kynetics.updatefactory.ddiclient.core.actors.UpdateManager$beforeStartReceive$1.invoke(Unknown Source:10)
D Update Factory Client: 	at com.kynetics.updatefactory.ddiclient.core.actors.AbstractActor$Companion$__workflow__$1.invokeSuspend(AbstractActor.kt:102)
 D Update Factory Client: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
D Update Factory Client: 	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
 D Update Factory Client: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
  D Update Factory Client: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
  D Update Factory Client: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
  D Update Factory Client: Send message ActorException to actor deploymentManager. [::0] Thread[DefaultDispatcher-worker-8,5,main]
I UpdateFactoryService: receive request to resume suspend state
 D Update Factory Client: Send message SetPing to actor connectionManager. [ConnectionManager$runningReceive$1:invokeSuspend:70] Thread[DefaultDispatcher-worker-7,5,main]
D Update Factory Client: Send message Ping to actor connectionManager. [ConnectionManager$startPing$$inlined$timer$1$lambda$1:invokeSuspend:169] Thread[DefaultDispatcher-worker-7,5,main]
 I Update Factory Client: Execute ping calls to the server... [ConnectionManager:onPing:134] Thread[DefaultDispatcher-worker-7,5,main]
 D Update Factory Client: onDeploymentActionDetailsChange() [::0] Thread[DefaultDispatcher-worker-7,5,main]
 I AndroidMessageListener: Polling
  D Update Factory Client: Response{protocol=http/1.1, code=200, message=OK, url=http:/DEFAULT/controller/v1/0965} [::0] Thread[DefaultDispatcher-worker-1,5,main]
I Update Factory Client: BaseResource is changed. Old ETag: , new ETag: "01ab3d298fdaaf20cebeb9d11640c47b9" [::0] Thread[DefaultDispatcher-worker-1,5,main]
 D Update Factory Client: onDeploymentActionDetailsChange(305, 0, ) [::0] Thread[DefaultDispatcher-worker-1,5,main]
 I AndroidMessageListener: UpdateAvailable(id=305)
D Update Factory Client: Response{protocol=http/1.1, code=200, message=OK, url=http:///DEFAULT/controller/v1/0965/deploymentBase/305?actionHistory=0} [::0] Thread[DefaultDispatcher-worker-1,5,main]
I Update Factory Client: Deployment is changed. Old ETag: , new ETag: "032f1a4e1d95f5e12300545ac988677de" [::0] Thread[DefaultDispatcher-worker-1,5,main]
  7064 D Update Factory Client: Send message DeploymentInfo to actor actionManager. [::0] Thread[DefaultDispatcher-worker-1,5,main]
 I UpdateFactoryService: receive request to resume suspend state
 D Update Factory Client: Send message SetPing to actor connectionManager. [ConnectionManager$runningReceive$1:invokeSuspend:70] Thread[DefaultDispatcher-worker-2,5,main]
D Update Factory Client: Send message Ping to actor connectionManager. [ConnectionManager$startPing$$inlined$timer$1$lambda$1:invokeSuspend:169] Thread[DefaultDispatcher-worker-2,5,main]
I Update Factory Client: Execute ping calls to the server... [ConnectionManager:onPing:134] Thread[DefaultDispatcher-wo`

**Comment by diegorondini** [comment]
Hi,

I'm sorry but we can't reproduce the issue you're having, it may be an issue of a specific device rather than an issue in the client.
Can you describe a way to reproduce it?

**Comment by diegorondini** [comment]
Hi,

can you try to reproduce with the 1.3.1 version of the client?

**Comment by diegorondini** [comment]
We cannot reproduce this issue. Closing for lack of feedback.
