### ISSUE TITLE
Connection error increased polling rate contrary to device configuration

### ISSUE THREAD

**Issue by eschoenawa** [Kynetics/uf-android-client#8]
After a device encountered a connection error while polling I discovered that the polling rate increased from the configured 30 seconds to 5 seconds (the configuration is not modified though).

Unfortunately, I don't have a log of the incident. Below you can see a screenshot from the test app I created to test the 3rd party integration. The top events are newer, you can see that before the error happens the service is only polling every 30 seconds (as configured, see configuration at the top of the screenshot) while after the error the polling interval is increased to 5 seconds.

![uf_faster_polling_after_exception](https://user-images.githubusercontent.com/7061368/127846681-54010b5e-9c58-4b61-8b2f-3f3104aff58a.png)

**Comment by diegorondini** [comment]
Thank you for your report.

There are some circumstances where the polling time configured by the server is not used by design. In case of connection issue the polling should be more frequent at first, and then evenutally backoff.

**Comment by eschoenawa** [comment]
I see, so this is intended behavior? In that case, this issue can be closed, although it's probably a good idea to add this to the documentation so this won't be reported again.

Feel free to close once you think this is resolved.

**Comment by diegorondini** [comment]
The [1.2.0 release](https://github.com/Kynetics/uf-android-client/releases/tag/v1.2.0) includes fixes for better download exceptions  management.

Moreover the polling time exceptions are now documented in:
https://docs.updatefactory.io/devices/android/android-client/#client-polling-time

Thanks for your patience
